---
# vars file for common
tomcat_path: /opt/SP/apps/tomcat
tomcat_url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.10/bin/apache-tomcat-9.0.10.tar.gz
clear_webapps: /opt/SP/apps/tomcat/webapps/ROOT
petclinic_war: petclinic.war
download_path: /opt/SP/apps
